name: iris-workshop-python
volumes:
  iris-workshop-python-data:
    driver: local
services:
  iris-workshop-python:
    image: containers.intersystems.com/intersystems/iris-community:2025.1
    container_name: iris-workshop-python
    hostname: iris-workshop-python
    volumes:
      - iris-workshop-python-data:/usr/irissys
      - ./iris/db:/db
      - ./iris/backup:/backup
      - ./iris/config:/config
    ports:
      - 52777:52773
      - 51777:51773
      - 1977:1972
    restart: unless-stopped
